development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
  pool: 5
  port: 5432
  username: prelaunchr
  password: travelmore
test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost
  pool: 5
  port: 5432
  username: prelaunchr
  password: travelmore
